/*
Tavus Developer API Collection

We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ReplicasApi,
  VideosApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { TavusCustom } from "./client-custom";

export class Tavus extends TavusCustom {
  readonly replicas: ReplicasApi;
  readonly videos: VideosApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.replicas = new ReplicasApi(configuration);
    this.videos = new VideosApi(configuration);
  }

}
