/*
Tavus Developer API Collection

We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReplicasListResponseDataInner
 */
export interface ReplicasListResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof ReplicasListResponseDataInner
     */
    'created_at'?: string;
    /**
     * A unique identifier for the replica.
     * @type {string}
     * @memberof ReplicasListResponseDataInner
     */
    'replica_id'?: string;
    /**
     * The name of the replica.
     * @type {string}
     * @memberof ReplicasListResponseDataInner
     */
    'replica_name'?: string;
    /**
     * The status of the replica.
     * @type {string}
     * @memberof ReplicasListResponseDataInner
     */
    'status'?: string;
    /**
     * A direct link to the video that will be used as the thumbnail for the replica.
     * @type {string}
     * @memberof ReplicasListResponseDataInner
     */
    'thumbnail_video_url'?: string;
    /**
     * The progress of the replica training.
     * @type {string}
     * @memberof ReplicasListResponseDataInner
     */
    'training_progress'?: string;
}

