/*
Tavus Developer API Collection

We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReplicasGetReplicaByIdResponse
 */
export interface ReplicasGetReplicaByIdResponse {
    /**
     * The date and time the replica was created.
     * @type {string}
     * @memberof ReplicasGetReplicaByIdResponse
     */
    'created_at'?: string;
    /**
     * If the replica has an error, this will contain the error message.
     * @type {string}
     * @memberof ReplicasGetReplicaByIdResponse
     */
    'error_message'?: string | null;
    /**
     * A unique identifier for the replica.
     * @type {string}
     * @memberof ReplicasGetReplicaByIdResponse
     */
    'replica_id'?: string;
    /**
     * The name of the replica.
     * @type {string}
     * @memberof ReplicasGetReplicaByIdResponse
     */
    'replica_name'?: string;
    /**
     * The status of the replica.
     * @type {string}
     * @memberof ReplicasGetReplicaByIdResponse
     */
    'status'?: string;
    /**
     * A direct link to the video that will be used as the thumbnail for the replica.
     * @type {string}
     * @memberof ReplicasGetReplicaByIdResponse
     */
    'thumbnail_video_url'?: string;
    /**
     * The progress of the replica training.
     * @type {string}
     * @memberof ReplicasGetReplicaByIdResponse
     */
    'training_progress'?: string;
    /**
     * The date and time of when the replica was last updated.
     * @type {string}
     * @memberof ReplicasGetReplicaByIdResponse
     */
    'updated_at'?: string;
}

