/*
Tavus Developer API Collection

We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReplicasCreateNewReplicaRequest
 */
export interface ReplicasCreateNewReplicaRequest {
    /**
     * A url that will receive a callback on completion of replica training or on error.
     * @type {string}
     * @memberof ReplicasCreateNewReplicaRequest
     */
    'callback_url'?: string;
    /**
     * A name for the replica.
     * @type {string}
     * @memberof ReplicasCreateNewReplicaRequest
     */
    'replica_name'?: string;
    /**
     * A direct link to a publicly accessible storage location such as an S3 bucket. This video will be used for replica training.
     * @type {string}
     * @memberof ReplicasCreateNewReplicaRequest
     */
    'train_video_url': string;
}

