/*
Tavus Developer API Collection

We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VideosGetAllResponseDataInner
 */
export interface VideosGetAllResponseDataInner {
    /**
     * A direct link to a video that is publicly accessible via a storage location such as an S3 bucket. This will be used as the background for the video. The video must be publicly accessible.
     * @type {string}
     * @memberof VideosGetAllResponseDataInner
     */
    'background_source_url'?: string;
    /**
     * A link to a website. This will be used as the background for the video. The website must be publicly accessible and properly formed.
     * @type {string}
     * @memberof VideosGetAllResponseDataInner
     */
    'background_url'?: string;
    /**
     * A unique identifier for the replica that will be used to generate the video.
     * @type {string}
     * @memberof VideosGetAllResponseDataInner
     */
    'replica_id'?: string;
    /**
     * A script to be used for the video.
     * @type {string}
     * @memberof VideosGetAllResponseDataInner
     */
    'script'?: string;
    /**
     * A name for the video.
     * @type {string}
     * @memberof VideosGetAllResponseDataInner
     */
    'video_name'?: string;
}

