/*
Tavus Developer API Collection

We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VideosCreateVideoFromReplicaAndScriptResponse
 */
export interface VideosCreateVideoFromReplicaAndScriptResponse {
    /**
     * The date and time the video was created.
     * @type {string}
     * @memberof VideosCreateVideoFromReplicaAndScriptResponse
     */
    'created_at'?: string;
    /**
     * A direct link to view your video once generation has completed, hosted by Tavus.
     * @type {string}
     * @memberof VideosCreateVideoFromReplicaAndScriptResponse
     */
    'hosted_url'?: string;
    /**
     * The status of the video.
     * @type {string}
     * @memberof VideosCreateVideoFromReplicaAndScriptResponse
     */
    'status'?: string;
    /**
     * A unique identifier for the video.
     * @type {string}
     * @memberof VideosCreateVideoFromReplicaAndScriptResponse
     */
    'video_id'?: string;
    /**
     * The name of the video.
     * @type {string}
     * @memberof VideosCreateVideoFromReplicaAndScriptResponse
     */
    'video_name'?: string;
}

