/*
Tavus Developer API Collection

We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VideosUpdateNameRequest
 */
export interface VideosUpdateNameRequest {
    /**
     * 
     * @type {string}
     * @memberof VideosUpdateNameRequest
     */
    'video_name': string;
}

